#!/usr/bin/env bash
# if there is no secord arg....echo 'error....'
# else ping given ip_addr five times

if [ $# -eq 1 ]
then
	ping -c 5 "$1"
else
	echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
fi

