#!/usr/bin/env bash
# Changes some configurations in the host file
# 	- localhost to 127.0.0.2
# 	- facebook.com to 8.8.8.8

cp /etc/hosts ~/hosts.new
echo "127.0.0.2		localhost" > ~/hosts.new
echo "8.8.8.8		facebook.com" >> ~/hosts.new
cp -f ~/hosts.new /etc/hosts

